spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/TeamsFinder
        registration:
          keycloak-client:
            provider: keycloak
            client-id: teamsfinder
            client-secret: 13c0d69f-5c7a-4e48-aaf2-eb89d16aa6d2
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    gateway:
      routes:
        - id: userWriteModule
          uri: lb://USER-WRITE-SERVICE
          predicates:
            - Path=/**
        - id: userReadModule
          uri: lb://USER-READ-SERVICE
          predicates:
            - Path=/**
  application:
    name: api-gateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9090